/**
 * Catalogo ISO 3166-1 alpha-2 usado por el bloqueo geografico y por los
 * formularios de retiro. Los codigos son la unica fuente de verdad: cualquier
 * valor que no este aqui se descarta antes de tocar la base de datos.
 */

export const COUNTRIES: ReadonlyArray<{ code: string; name: string }> = [
  { code: 'AD', name: 'Andorra' },
  { code: 'AE', name: 'Emiratos Arabes Unidos' },
  { code: 'AF', name: 'Afganistan' },
  { code: 'AG', name: 'Antigua y Barbuda' },
  { code: 'AI', name: 'Anguila' },
  { code: 'AL', name: 'Albania' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AO', name: 'Angola' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AS', name: 'Samoa Americana' },
  { code: 'AT', name: 'Austria' },
  { code: 'AU', name: 'Australia' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AX', name: 'Islas Aland' },
  { code: 'AZ', name: 'Azerbaiyan' },
  { code: 'BA', name: 'Bosnia y Herzegovina' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BD', name: 'Banglades' },
  { code: 'BE', name: 'Belgica' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BH', name: 'Barein' },
  { code: 'BI', name: 'Burundi' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BL', name: 'San Bartolome' },
  { code: 'BM', name: 'Bermudas' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BQ', name: 'Caribe Neerlandes' },
  { code: 'BR', name: 'Brasil' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BT', name: 'Butan' },
  { code: 'BW', name: 'Botsuana' },
  { code: 'BY', name: 'Bielorrusia' },
  { code: 'BZ', name: 'Belice' },
  { code: 'CA', name: 'Canada' },
  { code: 'CD', name: 'Republica Democratica del Congo' },
  { code: 'CF', name: 'Republica Centroafricana' },
  { code: 'CG', name: 'Congo' },
  { code: 'CH', name: 'Suiza' },
  { code: 'CI', name: 'Costa de Marfil' },
  { code: 'CK', name: 'Islas Cook' },
  { code: 'CL', name: 'Chile' },
  { code: 'CM', name: 'Camerun' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'CW', name: 'Curazao' },
  { code: 'CY', name: 'Chipre' },
  { code: 'CZ', name: 'Chequia' },
  { code: 'DE', name: 'Alemania' },
  { code: 'DJ', name: 'Yibuti' },
  { code: 'DK', name: 'Dinamarca' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Republica Dominicana' },
  { code: 'DZ', name: 'Argelia' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EE', name: 'Estonia' },
  { code: 'EG', name: 'Egipto' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'ES', name: 'Espana' },
  { code: 'ET', name: 'Etiopia' },
  { code: 'FI', name: 'Finlandia' },
  { code: 'FJ', name: 'Fiyi' },
  { code: 'FK', name: 'Islas Malvinas' },
  { code: 'FM', name: 'Micronesia' },
  { code: 'FO', name: 'Islas Feroe' },
  { code: 'FR', name: 'Francia' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GB', name: 'Reino Unido' },
  { code: 'GD', name: 'Granada' },
  { code: 'GE', name: 'Georgia' },
  { code: 'GF', name: 'Guayana Francesa' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GL', name: 'Groenlandia' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GP', name: 'Guadalupe' },
  { code: 'GQ', name: 'Guinea Ecuatorial' },
  { code: 'GR', name: 'Grecia' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GU', name: 'Guam' },
  { code: 'GW', name: 'Guinea-Bisau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HR', name: 'Croacia' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HU', name: 'Hungria' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'IL', name: 'Israel' },
  { code: 'IM', name: 'Isla de Man' },
  { code: 'IN', name: 'India' },
  { code: 'IQ', name: 'Irak' },
  { code: 'IR', name: 'Iran' },
  { code: 'IS', name: 'Islandia' },
  { code: 'IT', name: 'Italia' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JO', name: 'Jordania' },
  { code: 'JP', name: 'Japon' },
  { code: 'KE', name: 'Kenia' },
  { code: 'KG', name: 'Kirguistan' },
  { code: 'KH', name: 'Camboya' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KM', name: 'Comoras' },
  { code: 'KN', name: 'San Cristobal y Nieves' },
  { code: 'KP', name: 'Corea del Norte' },
  { code: 'KR', name: 'Corea del Sur' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KY', name: 'Islas Caiman' },
  { code: 'KZ', name: 'Kazajistan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LB', name: 'Libano' },
  { code: 'LC', name: 'Santa Lucia' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LS', name: 'Lesoto' },
  { code: 'LT', name: 'Lituania' },
  { code: 'LU', name: 'Luxemburgo' },
  { code: 'LV', name: 'Letonia' },
  { code: 'LY', name: 'Libia' },
  { code: 'MA', name: 'Marruecos' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MD', name: 'Moldavia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MF', name: 'San Martin' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MH', name: 'Islas Marshall' },
  { code: 'MK', name: 'Macedonia del Norte' },
  { code: 'ML', name: 'Mali' },
  { code: 'MM', name: 'Birmania' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'MO', name: 'Macao' },
  { code: 'MP', name: 'Islas Marianas del Norte' },
  { code: 'MQ', name: 'Martinica' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MT', name: 'Malta' },
  { code: 'MU', name: 'Mauricio' },
  { code: 'MV', name: 'Maldivas' },
  { code: 'MW', name: 'Malaui' },
  { code: 'MX', name: 'Mexico' },
  { code: 'MY', name: 'Malasia' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NC', name: 'Nueva Caledonia' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NL', name: 'Paises Bajos' },
  { code: 'NO', name: 'Noruega' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NZ', name: 'Nueva Zelanda' },
  { code: 'OM', name: 'Oman' },
  { code: 'PA', name: 'Panama' },
  { code: 'PE', name: 'Peru' },
  { code: 'PF', name: 'Polinesia Francesa' },
  { code: 'PG', name: 'Papua Nueva Guinea' },
  { code: 'PH', name: 'Filipinas' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PL', name: 'Polonia' },
  { code: 'PR', name: 'Puerto Rico' },
  { code: 'PS', name: 'Palestina' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PW', name: 'Palaos' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'QA', name: 'Catar' },
  { code: 'RE', name: 'Reunion' },
  { code: 'RO', name: 'Rumania' },
  { code: 'RS', name: 'Serbia' },
  { code: 'RU', name: 'Rusia' },
  { code: 'RW', name: 'Ruanda' },
  { code: 'SA', name: 'Arabia Saudi' },
  { code: 'SB', name: 'Islas Salomon' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SE', name: 'Suecia' },
  { code: 'SG', name: 'Singapur' },
  { code: 'SI', name: 'Eslovenia' },
  { code: 'SK', name: 'Eslovaquia' },
  { code: 'SL', name: 'Sierra Leona' },
  { code: 'SM', name: 'San Marino' },
  { code: 'SN', name: 'Senegal' },
  { code: 'SO', name: 'Somalia' },
  { code: 'SR', name: 'Surinam' },
  { code: 'SS', name: 'Sudan del Sur' },
  { code: 'ST', name: 'Santo Tome y Principe' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'SX', name: 'Sint Maarten' },
  { code: 'SY', name: 'Siria' },
  { code: 'SZ', name: 'Esuatini' },
  { code: 'TC', name: 'Islas Turcas y Caicos' },
  { code: 'TD', name: 'Chad' },
  { code: 'TG', name: 'Togo' },
  { code: 'TH', name: 'Tailandia' },
  { code: 'TJ', name: 'Tayikistan' },
  { code: 'TL', name: 'Timor Oriental' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TN', name: 'Tunez' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TR', name: 'Turquia' },
  { code: 'TT', name: 'Trinidad y Tobago' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'UA', name: 'Ucrania' },
  { code: 'UG', name: 'Uganda' },
  { code: 'US', name: 'Estados Unidos' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VA', name: 'Ciudad del Vaticano' },
  { code: 'VC', name: 'San Vicente y las Granadinas' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VG', name: 'Islas Virgenes Britanicas' },
  { code: 'VI', name: 'Islas Virgenes de EE. UU.' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'WS', name: 'Samoa' },
  { code: 'XK', name: 'Kosovo' },
  { code: 'YE', name: 'Yemen' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'ZA', name: 'Sudafrica' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabue' },
];

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c.name]));

/** Codigos validos, en mayusculas. */
export const COUNTRY_CODES: ReadonlySet<string> = new Set(BY_CODE.keys());

/**
 * Normaliza una entrada arbitraria a un codigo ISO valido, o null.
 * Acepta minusculas y espacios; rechaza cualquier cosa que no este en la lista.
 */
export function normalizeCountryCode(input: unknown): string | null {
  if (typeof input !== 'string') return null;
  const code = input.trim().toUpperCase();
  return COUNTRY_CODES.has(code) ? code : null;
}

/** Nombre legible de un codigo, o el propio codigo si es desconocido. */
export function countryName(code: string | null | undefined): string {
  if (!code) return 'Desconocido';
  return BY_CODE.get(code.toUpperCase()) ?? code.toUpperCase();
}

/** Bandera emoji a partir del codigo ISO (A-Z -> indicadores regionales). */
export function countryFlag(code: string): string {
  const upper = code.trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(upper)) return '';
  return String.fromCodePoint(
    ...[...upper].map((ch) => 0x1f1e6 + ch.charCodeAt(0) - 65),
  );
}
